# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Graceful
tagline:          'Graceful Lillian'
description:      'The personal site of Lillian Grace, CEO of <a href="http://figure.nz/" target="_blank">Figure.NZ</a>.'
url:              http://gracefullillian.com
baseurl:          /

author:
  name:           'Lillian Grace'
  url:            https://twitter.com/GracefulLillian

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/gracefullillian/web
